### ISSUE TITLE
Add an Example File

### ISSUE THREAD

**Issue by judah4** [theHedgehog0/fursona-schema#4]
There should be an example fursona file for a template and schema testing.

**Comment by theHedgehog0** [comment]
I've added a valid `example.json` file, and the schema has changed slightly(`profile-picture` has been renamed to `avatar`, as I feel it describes the same thing but is just a bit cleaner)

I think I'll want to add some invalid JSON files, I'll probably make an examples directory with various valid and invalid examples.
